name: Weather App CI

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'
        
jobs:
  app-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 16.15.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Test
        run: yarn test
