name: Trigger auto deployment for testweather

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/testweather-AutoDeployTrigger-83bbda7d-f376-4084-8508-ae17cc95c242.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.TESTWEATHER_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTWEATHER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: blueskiy/weatherapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTWEATHER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n testweather -g weather-app-blueskiy --server docker.io --username  ${{ secrets.TESTWEATHER_REGISTRY_USERNAME }} --password ${{ secrets.TESTWEATHER_REGISTRY_PASSWORD }}
            az containerapp update -n testweather -g weather-app-blueskiy --image blueskiy/weatherapp:${{ github.sha }}
